sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
branches:
  only:
    - master

before_install:
  - git clone https://github.com/keycloak/keycloak-nodejs-auth-utils.git
  - cd  keycloak-nodejs-auth-utils && npm install && npm link

install:
  - npm link keycloak-auth-utils
  - npm install
before_script:
   - ./scripts/start-server.sh
   - node test/app-fixture.js &
script: make
after_script:
   - ./scripts/stop-server.sh
   - kill -9 `cat pid.txt`
